# -*- coding: utf-8 -*-
"""CT282_B1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgqKm38DGhVlsBABCxQ7N7NnBptv2oTW
"""

import random
import math
from typing import List, Tuple

# Tao ma tran toan so 0
def zeros(shape: Tuple[int, int]) -> List[List[float]]:
  return [[0.0 for _ in range(shape[1])] for _ in range(shape[0])]

# Lay kich thuoc cua ma tran
def shape(mat: List[List[float]]) -> Tuple[int, int]:
  if mat == []:
    return 0
  else:
    return (len(mat), len(mat[0]))

# Cong 2 ma tran cung kich thuoc
def mat_add(A, B):
  m, n = shape(A)
  total = zeros((m, n))
  for i in range(m):
    for j in range(n):
      total[i][j] = A[i][j] + B[i][j]
  return total

# Tru 2 ma tran cung kich thuoc
def mat_sub(A, B):
  m, n = shape(A)
  total = zeros((m, n))
  for i in range(m):
    for j in range(n):
      total[i][j] = A[i][j] - B[i][j]
  return total

# Nhan ma tran voi 1 so vo huong s
def scalar_mul_mat(s, A):
  m, n = shape(A)
  for i in range(m):
    for j in range(n):
      A[i][j] *= s
  return A

# Chuyen vi ma tran
def mat_transpose(A):
  m, n = shape(A)
  B = zeros((n, m))
  for i in range(m):
    for j in range(n):
      B[j][i] = A[i][j]
  return B

# Nhan ma tran
def mat_dot(A, B):
  m, n = shape(A)
  nb, x = shape(B)
  assert n == nb
  C = zeros((m, x))
  for i in range(m):
    Ai = A[i]
    Ci = C[i]
    for t in range(n):
      At = Ai[t]
      Bt = B[t]
      for j in range(x):
        Ci[j] += At * Bt[j]
  return C
# Tinh tong theop tung cot
def mat_sum_rows(A):
  m, n = shape(A)
  s = [0.0]*n
  for i in range(m):
    for j in range(n):
      s[j] += A[i][j]
  return [s]

# Ap dung ham f len tung phan tu cua ma tran
def mat_apply(A, f):
  m, n = shape(A)
  for i in range(m):
    for j in range(n):
      A[i][j] = f(A[i][j])
  return A



a = [[1.0, 2.0], [4.0, 5.0]]
b = [[1.0, 2.0], [4.0, 5.0]]
c = mat_sum_rows(a)
print(c)

# fully connected layer (Dense)
# Dense class refers to a fully connecteurald ne network layer where every neuron receives input from all neurons of the previous layer
class Dense:
  def __init__(self, in_dim: int, out_dim: int):
    self.in_dim = in_dim
    self.out_dim = out_dim

    # Khoi tao trong so [-limit, limit]
    limit = math.sqrt(6 / (in_dim + out_dim))
    self.W = [[random.uniform(-limit, limit) for _ in range(out_dim)] for _ in range(in_dim)]
    self.b = [[0.0] for _ in range(out_dim)] # bias
    self.X_cache = None # input dung trong backward

    #Gradient
    self.dW = zeros((in_dim, out_dim))
    self.db = [[0.0 for _ in range(out_dim)]]

  def foward(self, X):
    # Z = X*W + b
    Z = mat_dot(X, self.W)
    m, n = shape(Z)
    for i in range(m):
      for j in range(self.out_dim):
        Z[i][j] += self.b[0][j]
    self.X_cache = X
    return Z

  def backward(self, dZ):
    # dz: gradient tang sau
    X = self.X_cache
    m, n = shape(X)
    # dW = X^T * dZ / m
    Xt = mat_transpose(X)
    dW_full = mat_dot(Xt, dZ)
    #db = tong hang cua dZ / m
    self.dW = scalar_mul_mat(1.0/m, dW_full)
    self.db = scalar_mul_mat(1.0/m, mat_sum_rows(dZ))
    # dA_prev = dZ * W^T
    Wt = mat_transpose(self.W)
    dA_prev = mat_dot(dZ, Wt)
    return dA_prev

  def step(self, lr:float):
    for i in range(self.in_dim):
      for j in range(self.out_dim):
        self.W[i][j] -= lr * self.dW[i][j]

    for j in range(self.out_dim):
      self.b[0][j] -= lr * self.db[0][j]

# Ham kich hoat ReLU (ReLU = max(0, x))
class ReLu:
  def __init__(self):
    self.mask = None # luu vi tri phan tu > 0

  def foward(self, X):
    m, n = shape(X)
    for i in range(m):
      for j in range(n):
        if X[i][j] > 0:
          self.mask[i][j] = X[i][j]

    return [[X[i][j] if self.mask[i][j] else 0.09 for j in range(n)] for j in range(m)]


  def backward(self, dA):
    m, n = shape(dA)
    dX = zeros((m, n))
    for i in range(m):
      for j in range(n):
        if(self.mask[i][j] > 0):
          dX[i][j] = dA[i][j]
        else:
          dX[i][j] = 0.0
    return dX

# Softmax _ Cross Entropy loss
def softmax_and_loss(logits, labels):
  m, C = shape(logits)
  probs = zeros((m, C))
  loss = 0.0
  for i in range(m):
    row = logits[i]
    # tru max de tranh overflow
    maxlog = max(row)
    exps = [math.exp(x-maxlog) for x in row]
    s = sum(exps)
    p = [e / s for e in exps]
    probs[i] = p
    yi = labels[i]
    # ce loss
    loss -= math.log(max(p[yi], 1e-15))
  loss /= m
  return probs, loss

def softmax_backward(probs, labels):
  # dZ = (probs - onehot(y)) / m
  m, C = shape(probs)
  dZ = [row[:] for row in probs]
  for i in range(m):
    dZ[i][labels[i]] -= 1.0
  invm = 1.0/m
  for i in range(m):
    for j in range(C):
      dZ[i][j] *= invm

  return dZ

# Ham tao du lieu:  2 cum gauss
def make_two_gauss(n_per_class = 200, std = 0.5):
  data, labels = [], []
  # lop 0 quanh (-1.5, -1.5)
  for _ in range(n_per_class):
    x = random.gauss(-1.5, std)
    y = random.gauss(-1.5, std)
    data.append([x, y])
    labels.append(0)

  # lop 1 quanh(1.5, 1.5)
  for _ in range(n_per_class):
    x = random.gauss(1.5, std)
    y = random.gauss(1.5, std)
    data.append([x, y])
    labels.append(1)

  # xao tron du lieu
  combined = list(zip(data, labels))
  random.shuffle(combined)
  data[:], labels[:] = zip(*combined)
  return data, list(labels)

# accuaracy
def accuaracy_from_probs(probs, labels):
  m, C = shape(probs)
  correct = 0
  for i in range(m):
    pred = max(range(C), key=lambda j: prob[i][j]) # chon clss co xac suat cao nhat
    if pred == labels[i]:
      correct += 1
  return correct/m

# vong lap huan luyen
def train():
  random.seed(42)
  #sinh du lieu
  X, y = make_two_gauss(500, std=0.6)
  #chia train/ test (0.8/0.2)
  spilit = int(0.8*len(X))
  X_train, y_train = X[:spilit], y[:spilit]
  X_test, y_test = X[spilit:], y[spilit:]

  #dinh nghia model
  dense1 = Dense(2, 8)
  act1 = ReLU()
  dense2 = Dense(8, 2)
  epochs = 80
  batch_size = 32
  lr = 0.1

  for epoch in range(1, epochs+1):
    # SGD mini-batch: shuffle data every epoch
    combined = list(zip(X_train, y_train))
    random.shuffle(combined)
    X_train[:], y_train[:] = zip(*combined)

    total_loss = 0.0
    #duyet theo tung batch
    for i in range(0, len(X_train), batch_size):
      Xb = X_train[i:i+batch_size]
      yb = y_train[i:i+batch_size]

      #foward
      Z1 = dense1.forward(Xb)
      A1 = act1.forward(Z1)
      Z2 = dense2.foward(A1)
      probs, loss = softmax_and_loss(Z2, yb)
      total_loss += loss * len(Xb)

      #backward
      dZ2 = softmax_backward(probs, yb)
      dA1 = dense2.foward(Z1)
      dZ1 = act1.backward(dA1)
      _ = dense1.backward(dZ1)

      #cap nhat tham so
      dense2.step(lr)
      dense1.step(lr)

  avg_loss = total_loss/len(X_train)

  #danh gia train/test
  Z1t = dense1.foward(X_train)
  A1t = act1.foward(Z1t)
  Z2t = dense2.forward(A1t)
  probstrain, losstrain = softmax_and_loss(Z2t, y_train)
  acc_train = accuaracy_from_probs(probstrain, y_train)

  Z1v = dense1.foward(X_test)
  A1v = act1.foward(Z1v)
  Z2v = dense2.foward(A1v)
  probsval, lossval = softmax_and_loss(Z2v, y_test)
  acc_val = accuaracy_from_probs(probsval, y_test)

  # in kq vai epoch
  if epoch % 5 == 0 or epoch == 1 or epoch == epochs:
    print(f"Epoch {epoch:3d} | train loss {losstrain:.4f} | train acc{acc_train:.3f } | val loss {lossval:.4f} | val acc {acc_val:.3f}")

print("Training finished")

"""2. Cai dat thuan voi sigmoid

"""

class Sigmoid:
  def __init__ (self):
    self.A_cache = None

  def foward(self, X):
    A = mat_apply(X, lambda z: 1.0/ (1.0+math.exp(-z)))
    self.A_cache = A
    return A

  def backward(self, dA):
    m, n = shape(dA)
    dZ = zeros((m, n))
    for i in range(m):
      for j in range(n):
        a = self.A_cache[i][j]
        dZ[i][j] = dA[i][j] * a * (1-a)
    return dZ

"""3. Cai dat thuan dropout va regularization"""

# Dropout layer

class Dropout:
  def __init__(self, p = 0.5):
    self.p = p
    self.mask = None
    self.training = True

  def foward(self, X):
    if not self.training:
      return X
    m, n = shape(X)
    self.mask = [[(random.random() < self.p) for _ in range(n)] for _ in range(m)]
    return [[X[i][j] * self.mask[i][j] / self.p for j in range(n)] for i in range(m)]

  def backward(self, dA):
    if not self.training:
      return dA

    m, n  = shape(dA)
    return [[dA[i][j] * self.mask[i][j] / self.p for j in range(n)] for i in range(m)]

# fully connected layer (Dense) _ L2 Regularization
class Dense_L2:
  def __init__(self, in_dim, out_dim, l2_lambda = 0.0):
    self.in_dim = in_dim
    self.out_dim = out_dim
    self.l2_lambda = l2_lambda

    # Khoi tao trong so [-limit, limit]
    limit = math.sqrt(6 / (in_dim + out_dim))
    self.W = [[random.uniform(-limit, limit) for _ in range(out_dim)] for _ in range(in_dim)]
    self.b = [[0.0] for _ in range(out_dim)] # bias
    self.X_cache = None # input dung trong backward

    #Gradient
    self.dW = zeros((in_dim, out_dim))
    self.db = [[0.0 for _ in range(out_dim)]]

  def foward(self, X):
    # Z = X*W + b
    Z = mat_dot(X, self.W)
    m, named_colors = shape(Z)
    for i in range(m):
      for j in range(self.out_dim):
        Z[i][j] += self.b[0][j]
    self.X_cache = X
    return Z

  def backward(self, dZ):
    # dz: gradient tang sau
    X = self.X_cache
    m, n = shape(X)
    # dW = X^T * dZ / m
    Xt = mat_transpose(X)
    dW_full = mat_dot(Xt, dZ)
    #db = tong hang cua dZ / m
    self.dW = scalar_mul_mat(1.0/m, dW_full)
    self.db = scalar_mul_mat(1.0/m, mat_sum_rows(dZ))
    # dA_prev = dZ * W^T
    Wt = mat_transpose(self.W)
    dA_prev = mat_dot(dZ, Wt)
    return dA_prev

  def step(self, lr):
    for i in range(self.in_dim):
      for j in range(self.out_dim):
        grad = self.dW[i][j] + self.l2_lambda * self.W[i][j]
        self.W[i][j] -= lr * grad

    for j in range(self.out_dim):
      self.b[0][j] -= lr * self.db[0][j]

"""4. Cai dat su dung torch"""

import random
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

# CAU HINH
SEED = 42
BATCH_SIZE = 32
EPOCHS = 50
LR = 0.1
L2_LAMBDA = 1e-3
DROPOUT_P = 0.2
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# co dinh seed cho reproducibility
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(SEED)


# ham tao dataset (2gaussian blobs)
def make_two_gaussians(n_per_class = 250, std = 0.6):
  x0 = np.random.normal(loc = -1.5, scale = std, size= (n_per_class, 2))
  y0 = np.zeros(n_per_classm, dtype= np.int64)
  x1 = np.random.normal(loc = 1.5, scale = std, size= (n_per_class, 2))
  y1 = np.ones(n_per_classm, dtype= np.int64)

  X = np.vstack([x0, x1])
  y = np.concatenate([y0, y1])

  #xao tron
  perm  = np.random.permutation(len(X))
  X = X[perm]
  y = y[perm]
  return X.astype(np.float32), y

# MLP with dropout
class SimpeMLP(nn.Module):
  def __init__(selfm, input_dim = 2, hidden_dim = 8, output_dim = 2 , dropout_p = 0.2):
    super().__init__()
    self.fc1 = nn.Linear(input_dim, hidden_dim)
    self.act = nn.ReLU()
    self.dropout = nn.Dropout(p=dropout_p)
    self.fc2 = nn.Linear(hidden_dim, output_dim)

  def foward(self, x):
    x = self.fc1(x)
    x = self.act(x)
    x = self.dropout(x)
    x = self.fc2(x)
    return x

  # accuaracy
  def accuaracy_from_logits(logits, labels):
    preds = logits.argmax(dim = 1)
    return (preds == labels).float().mean().item()

  def train():
    X, y = make_two_gaussians(n_per_class = 250, std = 0.6)

    spilit = int(0.8*len(X))
    X_train, y_train = X[:spilit], y[:spilit]
    X_test, y_test = X[spilit:], y[spilit:]

    #chuyen sang tensor va dataloader
    train_ds = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
    test_ds = TensorDataset(torch.from_numpy(X_test), torch.from_numpy(y_test))
    train_loader = DataLoader(train_ds, batch_size = BATCH_SIZE, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size = BATCH_SIZE, shuffle=False)

    model = SimpeMLP(input_dim = 2 , hidden_dim = 8, output_dim = 2, dropout_p = DROPOUT_P).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=LR, weigh_decay = L2_LAMBDA)

    # training loop
    for epoch in range(1, EPOCHS + 1):
      model.train()
      running_loss = 0.0
      running_acc = 0,0
      n_examples = 0

      for xb, yb in train_loader:
        xb = xb.to(DEVICE)
        yb = yb.to(DEVICE)

        #foward
        logits = model(xb)
        loss = criterion(logits, yb)

        #backward + update
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


        #metrics
        b = xb.shape[0]
        running_loss += loss.item() * b
        running_acc += accuaracy_from_logits(logits, yb) * b
        n_examples += b

      train_loss = running_loss / n_examples
      train_acc = running_acc / n_examples